- name: Add repository for php
  when: initial_setup
  ansible.builtin.shell: |
    apt install software-properties-common -y ; sleep 2 ; add-apt-repository ppa:ondrej/php
- name: Install php extensions
  when: initial_setup
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_php_extensions }}"
