- name: Download nginx exporter
  when: initial_setup
  ansible.builtin.shell: |
    cd /tmp ;
    wget https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.1/nginx-prometheus-exporter_1.4.1_linux_amd64.tar.gz ;
    tar xvfz nginx-prometheus-exporter_*.*_amd64.tar.gz ;
    mv nginx-prometheus-exporter /usr/local/bin/ ;
    useradd -rs /bin/false nginx_exporter ;
- name: Copy nginx status page conf to the server
  ansible.builtin.template:
    src: "../templates/nginx-status-page.conf.j2"
    dest: "/etc/nginx/conf.d/nginx-status-page.conf"
- name: Create nginx exporter service
  when: initial_setup
  ansible.builtin.shell: |
    cat << 'EOF' > /etc/systemd/system/nginx_exporter.service
    [Unit]
    Description=Nginx Exporter
    After=network.target
    [Service]
    User=nginx_exporter
    Group=nginx_exporter
    Type=simple
    ExecStart=/usr/local/bin/nginx-prometheus-exporter \
     --web.config.file=/etc/node_exporter_web.yaml \
     --nginx.scrape-uri=http://localhost:8082/nginx_status
    [Install]
    WantedBy=multi-user.target
    EOF
- name: Start and enable node_exporter
  when: initial_setup
  ansible.builtin.shell: |
    systemctl daemon-reload ;
    systemctl start nginx_exporter ;
    systemctl enable nginx_exporter ;
- name: Copy nginx_exporter nginx conf to the server
  ansible.builtin.template:
    src: "../templates/nginx-nginx_exporter.conf.j2"
    dest: "/etc/nginx/conf.d/nginx-exporter.conf"
